name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Add .NET Framework Developer Pack
        run: choco install netfx-4.7.2-devpack -y

      - name: Create Project
        run: |
          mkdir SpooferProject
          cd SpooferProject
          dotnet new winforms -n FortniteSpooferGUI -f net472
          cd FortniteSpooferGUI
          move ../../Program.cs .
          move ../../MainForm.cs .

      - name: Build
        run: |
          cd SpooferProject/FortniteSpooferGUI
          msbuild FortniteSpooferGUI.csproj /p:Configuration=Release

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: FortniteSpooferGUI
          path: SpooferProject/FortniteSpooferGUI/bin/Release/
